#!/bin/ksh
#

set -xv

#   BACKTRACK_1_DAY
MAIN_PATH=/umbc/epavlis/data01/LOCAL/magdak

#cd /umbc/epavlis/data01/LOCAL/magdak/INFILES/INF_OPS_MLTSAT
cd /umbc/epavlis/data01/LOCAL/magdak/INFILES/INF_OPS_MLTSAT

echo " OLD "

cat ARC_SETUP_OLD.DAILY

echo " NEW "

cat ARC_SETUP_NEW.DAILY

echo " NEXT "

cat ARC_SETUP_NXT.DAILY

echo " SOL No. "

cat SOLUTION_NO_FOR_LAST_RUN.DAILY


cp ARC_SETUP_OLD.DAILY ARC_SETUP_OLD.DAILYY.SAVE_BKTRK
cp ARC_SETUP_NEW.DAILY ARC_SETUP_NEW.DAILY.SAVE_BKTRK
cp ARC_SETUP_NXT.DAILY ARC_SETUP_NXT.DAILY.SAVE_BKTRK
cp ARC_SETUP_END.DAILY ARC_SETUP_END.DAILY.SAVE_BKTRK
cp SOLUTION_NO_FOR_LAST_RUN.DAILY SOLUTION_NO_FOR_LAST_RUN.DAILY.SAVE_BKTRK

#cat *.SAVE_BKTRK

cp ARC_SETUP_NEW.DAILY ARC_SETUP_NXT.DAILY
cp ARC_SETUP_OLD.DAILY ARC_SETUP_NEW.DAILY
cp ARC_SETUP_END_OLD.DAILY ARC_SETUP_END.DAILY 

read EYEAR EDOY Date_END_ARC END_ARC < $MAIN_PATH/INFILES/INF_OPS_MLTSAT/ARC_SETUP_END_OLD.DAILY
EDOY=` expr $EDOY - 1 `
#if [ "$EDOY" -eq "0" ]; then
#EDOY=366
#EYEAR=$EYEAR-1
#fi
$MAIN_PATH/scripts/ydoy2ymd $EYEAR $EDOY > tempo


# Convert to our file-name convention:
read Date_END_ARC < tempo
Y=`echo $Date_END_ARC|cut -c1-1`
MD=`echo $Date_END_ARC|cut -c2-6`

if [ "$Y" -eq "0" ]; then
  Y=z
elif [ "$Y" -eq "9" ]; then
  Y=n
elif [ "$Y" -eq "8" ]; then
  Y=e
elif [ "$Y" -eq "7" ]; then
  Y=s
elif [ "$Y" -eq "6" ]; then
  Y=x
elif [ "$Y" -eq "1" ]; then
  Y=o
elif [ "$Y" -eq "2" ]; then
  Y=w
fi

  END_ARC=${Y}${MD}

echo $EYEAR $EDOY $Date_END_ARC $END_ARC > tempo
mv tempo $MAIN_PATH/INFILES/INF_OPS_MLTSAT/ARC_SETUP_END_OLD.DAILY

read YEAR DOY Date_OLD_ARC OLD_ARC < $MAIN_PATH/INFILES/INF_OPS_MLTSAT/ARC_SETUP_OLD.DAILY
DOY=` expr $DOY - 1 `
if [ "$DOY" -eq "0" ]; then
YEAR=` expr $YEAR - 1 `
case $YEAR in

   1980) ndays=366 ;;       #  Leap year
   1984) ndays=366 ;;       #  Leap year
   1988) ndays=366 ;;       #  Leap year
   1992) ndays=366 ;;       #  Leap year
   1996) ndays=366 ;;       #  Leap year
   2000) ndays=366 ;;       #  Leap year
   2004) ndays=366 ;;       #  Leap year
   2008) ndays=366 ;;       #  Leap year
   2012) ndays=366 ;;       #  Leap year
   2016) ndays=366 ;;       #  Leap year
   2020) ndays=366 ;;       #  Leap year

      *) ndays=365 ;;       #  Default

esac

DOY=$ndays
fi

$MAIN_PATH/scripts/ydoy2ymd $YEAR $DOY > tempo

# Convert to our file-name convention:
read Date_OLD_ARC < tempo
Y=`echo $Date_OLD_ARC|cut -c1-1`
MD=`echo $Date_OLD_ARC|cut -c2-6`

if [ "$Y" -eq "0" ]; then
  Y=z
elif [ "$Y" -eq "9" ]; then
  Y=n
elif [ "$Y" -eq "8" ]; then
  Y=e
elif [ "$Y" -eq "7" ]; then
  Y=s
elif [ "$Y" -eq "6" ]; then
  Y=x
elif [ "$Y" -eq "1" ]; then
  Y=o

elif [ "$Y" -eq "2" ]; then
  Y=w
fi

  OLD_ARC=${Y}${MD}

echo $YEAR $DOY $Date_OLD_ARC $OLD_ARC > tempo
mv tempo $MAIN_PATH/INFILES/INF_OPS_MLTSAT/ARC_SETUP_OLD.DAILY


#cp  $MAIN_PATH/INFILES/INF_OPS_MLTSAT/ARC_SETUP*.DAILY  $MAIN_PATH/INFILES/INF_OPS_AS_D/.


chmod 777 ARC_SETUP_OLD.DAILY ARC_SETUP_NEW.DAILY ARC_SETUP_NXT.DAILY SOLUTION_NO_FOR_LAST_RUN.DAILY 

echo " ********************************************* "
echo " ********************************************* "

exit 0
