#!/bin/ksh
#

${SCR_DBG}set -vx
set -xv

#   GET_ELEMS_ALL

#             CASE to be either null, "WEEKLY", "MONTHLY", etc

SCR_NAME=GET_ELEMS_ALL
SCR_PARM=10
SCR_LIST="infile SV ITR VER GTR CASE PROJ SUBSOL DELETE INSERT"
SCR_VERS=030825.0


if [ `expr $#` -lt $SCR_PARM ]; then
   echo "Usage: $SCR_NAME ${SCR_LIST}\007"
   exit 101
fi

DateTime=`date '+DATE: %m/%d/%y  TIME: %H:%M:%S'`

echo " # "
echo " #  $SCR_NAME $* "
echo " # "
echo " #  Version $SCR_VERS "
echo " # "
echo " #  Run Date $DateTime "
echo " # "


infile=$1
SV=$2
ITR=$3
VER=$4
GTR=${5:-3}
CASE=${6:-WEEKLY}
PROJ=${7:-PP6}
SUBSOL=${8:-A}
DELETE=${9:-OUT}
INSERT=${10:-NONE}


  if [ "$SV" = "L1" ]; then

  DSK=umbc/epavlis/data01/LOCAL/magdak/MISSIONS
  sat=GISL1
  SATDEL=GISLV
  satn=7603901

  elif [ "$SV" = "L2" ]; then

  DSK=umbc/epavlis/data01/LOCAL/magdak/MISSIONS
  sat=GISL2
  SATDEL=GISLV
  satn=9207002
  
  elif [ "$SV" = "E1" ]; then

  DSK=umbc/epavlis/data01/LOCAL/magdak/MISSIONS
  sat=ETA1
  SATDEL=ETAV
  satn=8900103

  elif [ "$SV" = "E2" ]; then

  DSK=umbc/epavlis/data01/LOCAL/magdak/MISSIONS
  sat=ETA2
  SATDEL=ETAV
  satn=8903903

  elif [ "$SV" = "CHAMP" ]; then

  DSK=umbc/epavlis/data01/LOCAL/magdak/MISSIONS
  sat=CHAMP
  SATDEL=$sat
  satn=0309002

  elif [ "$SV" = "STARL" ]; then

  DSK=umbc/epavlis/data01/LOCAL/magdak/MISSIONS
  sat=STARL
  SATDEL=$sat
  satn=8903903
  elif [ "$SV" = "STELLA" ]; then

  DSK=umbc/epavlis/data01/LOCAL/magdak/MISSIONS
  sat=STELLA
  SATDEL=$sat
  satn=9306102

  elif [ "$SV" = "GFZ" ]; then

  DSK=umbc/epavlis/data01/LOCAL/magdak/MISSIONS
  sat=GFZ
  SATDEL=$sat
  satn=8601795
  PROJ=

  elif [ "$SV" = "AJISI" ]; then

  DSK=umbc/epavlis/data01/LOCAL/magdak/MISSIONS
  sat=AJISI
  SATDEL=$sat
  satn=8903903

  elif [ "$SV" = " ERS1" ]; then

  DSK=umbc/epavlis/data01/LOCAL/magdak/MISSIONS
  sat=ERS1
  SATDEL=$sat
  satn=8903903

  elif [ "$SV" = "TP" ]; then

  DSK=umbc/epavlis/data01/LOCAL/magdak/MISSIONS
  sat=TP
  SATDEL=$sat
  satn=8903903
  elif [ "$SV" = "MLTSAT" ]; then

  DSK=umbc/epavlis/data01/LOCAL/magdak/MISSIONS
  sat=MLTSAT
  SATDEL=$sat
#  satn=8903903

  fi

export satn



disk1=/${DSK}/$sat/punchdout/DR/$CASE
#disk1=/${DSK}/$sat/punchdout/EMT/$CASE

cd $disk1

while read file new_file
do

gzip -d  ${file}.${VER}1.gz
cat ${file}.${VER}1 > t00
gzip -9 ${file}.${VER}1

#gzcat ${file}.${VER}1 > t00

##

#arcline=`sed -n "/\/ARC\/    1 1../=" t00 `
arcline=`sed -n "/\/ARC\/    1 3 0/=" t00 `

frstline=`expr $arcline + 1`

sed -n "${frstline},\$p" t00 > t1

 grep "^ELEMS" t1 > $MAIN_PATH/INFILES/INF_OPS_MLTSAT/ELEMS_${sat}.${new_file}

done < $MAIN_PATH/INFILES/INF_OPS_MLTSAT/$infile

\rm t1 t00

