#!/bin/ksh
##                                                               ecp 000203
## Usage: MAKE_4MBIAS svn
##
#


${SCR_DBG}set -vx
set -xv

# Usage: MAKE_NEW_ARC svn case year 

#if [ `expr $#` -gt 3 ]; then
#   echo "Usage: MAKE_NEW_ARC svn case year 2> script_out \007"
#   exit 100
#fi

#    MAKE_NEW_ARC 

SCR_NAME=MAKE_NEW_ARC
SCR_PARM=3
SCR_LIST="svn case year"
SCR_VERS=030902.0


if [ `expr $#` -lt $SCR_PARM ]; then
   echo "Usage: $SCR_NAME ${SCR_LIST}\007"
   exit 101
fi

DateTime=`date '+DATE: %m/%d/%y  TIME: %H:%M:%S'`

echo " # "
echo " #  $SCR_NAME $* "
echo " # "
echo " #  Version $SCR_VERS "
echo " # "
echo " #  Run Date $DateTime "
echo " # "


svn=${1:-GISL1}
case=${2:-WEEKLY}
year=${3:-2003}
ARC=${4:-STARL}
#day=${4:-365}



if [ "$svn" = "GISL1" ]; then

   no=7603901
   disk=umbc/epavlis/data01/LOCAL/magdak/MISSIONS

   infile=$MAIN_PATH/INFILES/ARC_INFO_L.${case}
   sat=${svn}

elif [ "$svn" = "GISL2" ]; then

   no=9207002
   disk=umbc/epavlis/data01/LOCAL/magdak/MISSIONS

   infile=$MAIN_PATH/INFILES/ARC_INFO_L.${case}
   sat=${svn}

elif [ "$svn" = "ETA1" ]; then

   no=8900103
   disk=umbc/epavlis/data01/LOCAL/magdak/MISSIONS

   infile=$MAIN_PATH/INFILES/ARC_INFO_E.${case}
   sat=${svn}

elif [ "$svn" = "ETA2" ]; then

   no=8903903
   disk=umbc/epavlis/data01/LOCAL/magdak/MISSIONS

   infile=$MAIN_PATH/INFILES/ARC_INFO_E.${case}
   sat=${svn}

elif [ "$svn" = "CHAMP" ]; then

   no=0003902
   disk=umbc/epavlis/data01/LOCAL/magdak/MISSIONS

   infile=$MAIN_PATH/INFILES/ARC_INFO_CH.${case}
   sat=${svn}

elif [ "$svn" = "STARL" ]; then

   no=7501001
   disk=umbc/epavlis/data01/LOCAL/magdak/MISSIONS

   infile=$MAIN_PATH/INFILES/INF_OPS_AS/ARC_INFO_S.${case}
   sat=${svn}

elif [ "$svn" = "STELLA" ]; then

   no=9306102
   disk=umbc/epavlis/data01/LOCAL/magdak/MISSIONS

   infile=$MAIN_PATH/INFILES/INF_OPS_STELLA/ARC_INFO_S.${case}
   sat=${svn}

elif [ "$svn" = "AJISI" ]; then

   no=8606101
   disk=umbc/epavlis/data01/LOCAL/magdak/MISSIONS

   infile=$MAIN_PATH/INFILES/INF_OPS_AS/ARC_INFO_A.${case}
   sat=${svn}

elif [ "$svn" = "ERS1" ]; then

   no=9105001
   disk=umbc/epavlis/data01/LOCAL/magdak/MISSIONS

   infile=$MAIN_PATH/INFILES/ARC_INFO_ER1.${case}
   sat=${svn}

elif [ "$svn" = "TP" ]; then

   no=9205201
   disk=umbc/epavlis/data01/LOCAL/magdak/MISSIONS

   infile=$MAIN_PATH/INFILES/ARC_INFO_TP.${case}
   sat=${svn}
elif [ "$svn" = "MLTSAT" ]; then

   no=9205201
   disk=umbc/epavlis/data01/LOCAL/magdak/MISSIONS


   infile=$MAIN_PATH/INFILES/INF_OPS_MLTSAT/ARC_INFO_MLTSAT.${case}
   sat=${svn}
echo $disk $infile
fi

#
# execute job
#


disk1=/$disk/$sat/d_base/trnd/DR/$case
disk2=/$disk/$sat/d_base/bias
disk3=/$disk/$sat/d_base/attp
disk4=/$disk/d_base/sgms

mkdir -p $disk1
mkdir -p $disk2
mkdir -p $disk3
mkdir -p $disk4

cd $disk1

#$SCRIPTS/MAKE_4MBIAS ${sat}

# Now the bias master is locally in "all_bias.MASTER"
cat /${disk}/${sat}/d_base/bias/all_bias.MASTER_200301  > all_bias.MASTER_200301
cat $MAIN_PATH/INFILES/INF_OPS_MLTSAT/MASTER_${case}.${sat} > t1



# Now the bias master is locally in "all_OBSCOR.MASTER"
#cat /${disk}/${sat}/d_base/obsc/OBS > all_OBSCOR.MASTER 
# Now the obscor is locally in "all_OBSCOR.MASTER"


    while read file bgn end nd ac1 ac2 prev
#o91229  191229  200105       2  200101  200105
#w00308  200308  200315       2  200311  200315   200301


    do
    grep -v -e EPOCH -e ELEMS -e SATPAR -e THRDRG t1 > t0
    arcline=`sed -n "/REFSYS/=" t0 `
    nextline=`expr $arcline + 1`
    sed -n "1,${arcline}p" t0 > t1a

#    sed -n "1,\$p" $MAIN_PATH/INFILES/INF_OPS_MLTSAT/ARC_SETUP_EPOCHS.$case >> t1a
    sed -n "1,\$p" $MAIN_PATH/INFILES/INF_OPS_MLTSAT/ELEMS_${sat}.$file     >> t1a

sed -e "s/EPOCH               ......   0 0.0000000......   0 0.0000000......   0 0.0000000/EPOCH               RRRRRR   0 0.0000000SSSSSS   0 0.0000000PPPPPP   0 0.0000000/" t1a > t1aa
cp t1aa ttttt
cp t1aa t1a
    arcline=`sed -n "/ALBEDO/=" t0 `
    lastline=`expr $arcline - 1`
    sed -n "${nextline},${lastline}p" t0          >> t1a
    sed -n "1,\$p" all_bias.MASTER_200301 >> t1a #t2

    sed -e "s/AAAAAA/${ac1}/g" -e "s/BBBBBB/${ac2}/g" -e "s/RRRRRR/${prev}/" t1a > t2


#    sed -n "1,\$p" all_bias.MASTER >> t2

#    sed -n "1,\$p" all_OBSCOR.MASTER >> t2

    nextline=`sed -n "/PREPRO/=" t0 `
    lastline=`expr $nextline + 1`
    
    sed -n "${arcline},${nextline}p" t0 >> t2
    
#    sed -n "1,\$p" all_OBSCOR.MASTER >> t2

    sed -n "1,\$p" $disk4/MASTER_SIGMA.current >> t2
    
    sed -n "${lastline},\$p" t0 >> t2

    sed -e "s/SSSSSS/${bgn}/g" -e "s/PPPPPP/${end}/g" t2 > t1b


printf "$bgn" > data
cut -c1-2 data > year
cut -c3-4 data > month
cut -c5-6 data > day
read YY < year
read MM < month
read DD < day
if [ "${YY}" -gt "50" -a "${YY}" -le "99" ];then
arc_yy=`expr ${YY} + 1900 `
elif [ "${YY}" -ge "00" -a "${YY}" -le "50" ];then
arc_yy=`expr ${YY} + 2000 `
fi
YY=${arc_yy}
MM=$(echo $MM | sed 's/^0*//')
DD=$(echo $DD | sed 's/^0*//')
/umbc/epavlis/data01/LOCAL/magdak/scripts/ymd2ydoy  $YY $MM $DD > data2
read stop < data2
cut -c1-2 data2 > year
cut -c3-5 data2 > yday
read YY < year
read YDD < yday
YDDS=$YDD
if [ "${YY}" -gt "50" -a "${YY}" -le "99" ];then
arc_yy=`expr ${YY} + 1900 `
elif [ "${YY}" -ge "00" -a "${YY}" -le "50" ];then
arc_yy=`expr ${YY} + 2000 `
fi
YY=${arc_yy}
YY2=${arc_yy}
YDD1=`expr ${YDDS} + 1 `
if [ "${YDD1}" -gt "365" ];then
/umbc/epavlis/data01/LOCAL/magdak/scripts/ymd2ydoy  $YY2 12 31 > dataD2
read stop < dataD2
cut -c1-2 dataD2 > yearD2
cut -c3-5 dataD2 > ydayD2
read YYD < yearD2
read YDDA < ydayD2
nn=`expr $YDD1 - $YDDA `
if [ "${nn}" -eq "0" ];then
nn2=$YYD
nn=366
else
nn2=`expr $YYD + 1 `
fi
YY=$nn2
YDD1=$nn
fi

/umbc/epavlis/data01/LOCAL/magdak/scripts/ydoy2ymd $YY2 $YDD1 > STOP1
read dd1 < STOP1

YDD1=`expr ${YDDS} + 2 `
if [ "${YDD1}" -gt "365" ];then
/umbc/epavlis/data01/LOCAL/magdak/scripts/ymd2ydoy  $YY2 12 31 > dataD2
read stop < dataD2
cut -c1-2 dataD2 > yearD2
cut -c3-5 dataD2 > ydayD2
read YYD < yearD2
read YDDA < ydayD2
nn=`expr $YDD1 - $YDDA `
if [ "${nn}" -eq "0" ];then                                                                                                   
nn2=$YYD                                                                                                                      
nn=366                                                                                                                        
else                                                                                                                          
nn2=`expr $YYD + 1 `
fi  
YY=$nn2
YDD1=$nn
fi
/umbc/epavlis/data01/LOCAL/magdak/scripts/ydoy2ymd $YY $YDD1 > STOP2
read dd2 < STOP2

YDD1=`expr ${YDDS} + 3 `
if [ "${YDD1}" -gt "365" ];then
/umbc/epavlis/data01/LOCAL/magdak/scripts/ymd2ydoy  $YY2 12 31 > dataD2
read stop < dataD2
cut -c1-2 dataD2 > yearD2
cut -c3-5 dataD2 > ydayD2
read YYD < yearD2
read YDDA < ydayD2
nn=`expr $YDD1 - $YDDA `
if [ "${nn}" -eq "0" ];then                                                                                                   
nn2=$YYD                                                                                                                      
nn=366                                                                                                                        
else                                                                                                                          
nn2=`expr $YYD + 1 `
fi  
YY=$nn2
YDD1=$nn
fi
/umbc/epavlis/data01/LOCAL/magdak/scripts/ydoy2ymd $YY $YDD1 > STOP3
read dd3 < STOP3

YDD1=`expr ${YDDS} + 4 `
if [ "${YDD1}" -gt "365" ];then
/umbc/epavlis/data01/LOCAL/magdak/scripts/ymd2ydoy  $YY2 12 31 > dataD2
read stop < dataD2
cut -c1-2 dataD2 > yearD2
cut -c3-5 dataD2 > ydayD2
read YYD < yearD2
read YDDA < ydayD2
nn=`expr $YDD1 - $YDDA `
if [ "${nn}" -eq "0" ];then                                                                                                   
nn2=$YYD                                                                                                                      
nn=366                                                                                                                        
else                                                                                                                          
nn2=`expr $YYD + 1 `
fi  
YY=$nn2
YDD1=$nn
fi
/umbc/epavlis/data01/LOCAL/magdak/scripts/ydoy2ymd $YY $YDD1 > STOP4
read dd4 < STOP4

YDD1=`expr ${YDDS} + 5 `
if [ "${YDD1}" -gt "365" ];then
/umbc/epavlis/data01/LOCAL/magdak/scripts/ymd2ydoy  $YY2 12 31 > dataD2
read stop < dataD2
cut -c1-2 dataD2 > yearD2
cut -c3-5 dataD2 > ydayD2
read YYD < yearD2
read YDDA < ydayD2
nn=`expr $YDD1 - $YDDA `
if [ "${nn}" -eq "0" ];then                                                                                                   
nn2=$YYD                                                                                                                      
nn=366                                                                                                                        
else                                                                                                                          
nn2=`expr $YYD + 1 `
fi  
YY=$nn2
YDD1=$nn
fi
/umbc/epavlis/data01/LOCAL/magdak/scripts/ydoy2ymd $YY $YDD1 > STOP5
read dd5 < STOP5

YDD1=`expr ${YDDS} + 6 `
if [ "${YDD1}" -gt "365" ];then
/umbc/epavlis/data01/LOCAL/magdak/scripts/ymd2ydoy  $YY2 12 31 > dataD2
read stop < dataD2
cut -c1-2 dataD2 > yearD2
cut -c3-5 dataD2 > ydayD2
read YYD < yearD2
read YDDA < ydayD2
nn=`expr $YDD1 - $YDDA `
if [ "${nn}" -eq "0" ];then                                                                                                   
nn2=$YYD                                                                                                                      
nn=366                                                                                                                        
else                                                                                                                          
nn2=`expr $YYD + 1 `
fi  
YY=$nn2
YDD1=$nn
fi
/umbc/epavlis/data01/LOCAL/magdak/scripts/ydoy2ymd $YY $YDD1 > STOP6
read dd6 < STOP6



sed -e "s/aaaaaa/$bgn/g" t1b > tt2
sed -e "s/bbbbbb/$dd1/g" tt2 > tt3
sed -e "s/cccccc/$dd2/g" tt3 > tt4
sed -e "s/dddddd/$dd3/g" tt4 > tt5
sed -e "s/eeeeee/$dd4/g" tt5 > tt6
sed -e "s/ffffff/$dd5/g" tt6 > tt7
sed -e "s/gggggg/$dd6/g" tt7 > tt8
    mv tt8 $disk1/${file}

    done < $infile



#sed -e "s/600101000000.002012310000/${Date_NEW_ARC}000000.00${Date_NXT_ARC}0000/" ftn05 > ftn05M
#mv ftn05M ftn05
#
#



\rm t2 t0 t1a t1 all_*.MASTER tt* STOP* year* data* day month t1b yday

exit 0

