#!/bin/ksh
#                                                               ecp 000203      
# Usage: MAKE_4MBIAS svn 
#
 
${SCR_DBG}set -vx
set -xv

#if [ `expr $#` -gt 1 ]; then
#   echo "Usage: MAKE_4MBIAS svn 2> script_out \007"
#   exit 100
#fi

SCR_NAME=MAKE_4MBIAS
SCR_PARM=0
SCR_LIST="svn"
SCR_VERS=030825.0


if [ `expr $#` -lt $SCR_PARM ]; then
   echo "Usage: $SCR_NAME ${SCR_LIST}\007"
   exit 101
fi

DateTime=`date '+DATE: %m/%d/%y  TIME: %H:%M:%S'`

echo " # "
echo " #  $SCR_NAME $* "
echo " # "
echo " #  Version $SCR_VERS "
echo " # "
echo " #  Run Date $DateTime "
echo " # "


svn=$1
svn=MLTSAT
MAIN_PATH=/umbc/epavlis/data01/LOCAL/magdak

if [ "$svn" = "GISL1" ]; then

   no=7603901
   disk=umbc/epavlis/data01/LOCAL/magdak/MISSIONS

   sat=${svn}

elif [ "$svn" = "GISL2" ]; then

   no=9207002
   disk=umbc/epavlis/data01/LOCAL/magdak/MISSIONS

   sat=${svn}

elif [ "$svn" = "ETA1" ]; then

   no=8900103
   disk=umbc/epavlis/data01/LOCAL/magdak/MISSIONS

   sat=${svn}

elif [ "$svn" = "ETA2" ]; then

   no=8903903
   disk=umbc/epavlis/data01/LOCAL/magdak/MISSIONS

   sat=${svn}

elif [ "$svn" = "CHAMP" ]; then

   no=0003902
   disk=space/MISSIONS

   sat=${svn}

elif [ "$svn" = "STARL" ]; then

   no=7501001
   disk=space/MISSIONS

   sat=${svn}

elif [ "$svn" = "AJISI" ]; then

   no=8606101
   disk=space/MISSIONS

   sat=${svn}

elif [ "$svn" = "ERS1" ]; then

   no=9105001
   disk=space/MISSIONS

   sat=${svn}

elif [ "$svn" = "TP" ]; then

   no=9205201
   disk=space/MISSIONS

   sat=${svn}
elif [ "$svn" = "MLTSAT" ]; then

   no=9205201
   disk=umbc/epavlis/data01/LOCAL/magdak/MISSIONS

   sat=${svn}

fi

site_file=SITE.4mbias
site_file=SITE.4mbias_current_ALL
site_file=SITE.4mbias_current_ALL_20200228
site_file=SITE.4mbias_current_ALL_2020301

#
# execute job
#


path0=/$disk/d_base
where=/${disk}/$sat/d_base/bias

\rm b051 b151 b500 b900


cat $path0/data/SITE/$site_file > b0

cat $MAIN_PATH/INFILES/MAKE_4MBIAS.in_MLTSAT    > btmplt

while read site sigma
do

sed -e "s/CCCCCCCC/$site/g" -e "s/TTT/051/g" -e "s/AAAAAAA/$sigma/g"  btmplt >> b051
#sed -e "s/CCCCCCCC/$site/g" -e "s/TTT/151/g" -e "s/AAAAAAA/.10D-20/g" btmplt >> b151
#sed -e "s/CCCCCCCC/$site/g" -e "s/TTT/900/g" -e "s/AAAAAAA/.10D-15/g" btmplt >> b900

done < b0

#  Set the start/stop dates now:


cat b051 b151 b900  > all_bias.MASTER_20301
cp all_bias.MASTER_20301 $where/ 


#  Set the start/stop dates now:

#cat b051 b151 b500 b900 > all_bias.MASTER
#cat b051 b151  b900 > all_bias.MASTER


#sed -e "s/SSSSSS/$start/g" -e "s/PPPPPP/$stop/g" all_bias > arc_bias

#cp arc_bias $where/$arc

#gzip -f $where/$arc

\rm btmplt b0 b051 b151 b500 b900 

exit 0
